name: Project workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and deploy project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Cache build files
        uses: actions/cache@v1
        with:
          path: build
          key: ${{ runner.OS }}-build-${{ hashFiles('**/*.kt') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-

      - name: Build and deploy docker image
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: ./gradlew -Djib.allowInsecureRegistries=true jib

      - name: Extract application version to vars file
        run: .ci/export_application_version_to_env.sh

      - name: Update application with Portainer API
        run: .ci/portainer_update_service.sh ${{secrets.MPEIX_PORTAINER_USER}} ${{secrets.MPEIX_PORTAINER_PASSWORD}} ${{secrets.PORTAINER_URL}} ${{secrets.DEV_API_ENDPOINT_ID}} "mpeix_schedule" "manager.kekmech.com:5000/mpeix-schedule:${{env.APPLICATION_VERSION}}" "${{env.REGISTRY_AUTH_TOKEN}}"

